---
- hosts: tag_ACS730_Group5
  gather_facts: True
  become: yes
  vars:
    source_file: ./index.html
    dest_file: /var/www/html
    
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/ec2-user/environment/final/webserver/group5
  tasks:
    - name: Install Apache Web Server
      yum:
        name: httpd
        state: latest
    - name: Start Apache Web Server
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Copy index1.html
      copy:
        src: "{{ source_file }}"
        dest: "{{ dest_file }}"
      notify: Restart Apache
  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
    - name: Print result variable
      debug:
        var: result
    - name: Print debug message
      debug:
        msg: The result was {{ result }}
        
    - name: Print result variable
      debug: 
        var: result
    
    - name: Print debug message
      debug: 
        msg: "The result was {{ result }}"
      