name: build
on:
  push:
    branches: ["dev", "prod"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run IaC Scan
        uses: aquasecurity/action@master
        with:
          scan-type: 'config'
          ignore-unfixed: false
          format: 'sarif'
          output: 'results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'results.sarif'
          category: 'code'
